# Generated by Django 4.0.3 on 2022-04-05 23:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email_from', models.CharField(max_length=50)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('bcc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('reply_to', models.EmailField(default=None, max_length=254)),
                ('sent_date', models.DateTimeField(default=None)),
                ('date', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailapp.mailbox')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailapp.template')),
            ],
        ),
    ]
