# Generated by Django 4.0.3 on 2022-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.CharField(max_length=50),
        ),
    ]
