# Generated by Django 4.0.3 on 2022-04-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_remove_email_id_alter_email_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='uuid',
            new_name='id',
        ),
    ]
