# Generated by Django 4.0.3 on 2022-04-10 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_alter_email_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
    ]
